Better error message on missing textalpha.effect file
If the file .../obs-plugins/obs-text-pthread/textalpha.effect is
missing, instead of this cryptic error message:

  error: [obs-text-pthread] Cannot load '(null)'

produce this more informative error message instead:

  error: [obs-text-pthread] Cannot find module file 'textalpha.effect'